### ISSUE TITLE
bug: `NodeInfo > Full > Private Net > local story` is broken

### ISSUE THREAD

**Issue by marcgarreau** [ethereum/ethereum-react-components#105]
`Cannot read property 'syncMode' of undefined`

See [storybook](https://ethereum.github.io/ethereum-react-components/?selectedKind=Network%2FNode%20Info%2FFull%2FPrivate%20Net&selectedStory=local&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

**Comment by ryanio** [comment]
Thanks for the catch, PR fix incoming
