### ISSUE TITLE
request for license

### ISSUE THREAD

**Issue by MareoRaft** [ethereum/ethereum-react-components#142]
Your repo has no listed license, which means it is protected under copyright (see https://choosealicense.com/no-permission/ for full details).  Was this your intention?

I was hoping to use one of your components (the Identicon component) for one of my projects, but I cannot without a license such as the MIT license.

**Comment by marcgarreau** [comment]
thanks for the note and interest in the lib - will add an MIT or similar license as soon as I can get around to it.

**Comment by bbenligiray** [comment]
Any updates on this?

**Comment by PhilippLgh** [comment]
@marcgarreau would like to archive this repo but guess it makes sense to add a license anyways

**Comment by PhilippLgh** [comment]
added MIT license: https://github.com/ethereum/ethereum-react-components/commit/64dacc6db25feab44de0782342b5b63ad08cd4bf
